### ISSUE TITLE
Visual Business Model Canvas

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#10]
Please create a visual business model canvas. Each field of the table should summarize your business in a few bullet points.

**Comment by KylePFisher** [comment]
The README.md now has a business model canvas.

**Comment by GeorgLink** [comment]
Please use the Business Model Canvas layout for displaying it. Something like the [in this gist](https://gist.github.com/pierrebeaucamp/fa2fec4f859d8d9ce3d0)
