### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#15]
Please include a list of channels in addition to the description you already have. Suggestion to split the description into one paragraph for each channel. Describe how each channel helps to have the kind of customer relationship you seek.

**Comment by KylePFisher** [comment]
Thanks for the feedback, we've made a better up-front description of our communication channels that can be found at https://github.com/KylePFisher/CIST2100/blob/master/T2/channels.md#summary-of-channels

**Comment by GeorgLink** [comment]
Looks good. See #20
