### ISSUE TITLE
Customer Relationships

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#16]
Please change the order, starting with the overall customer relationship you seek and then separate paragraphs for different ways you achieve that relationship.

**Comment by KylePFisher** [comment]
Good point, there should be a clearer description of our relationship before jumping into channels at this section here: https://github.com/KylePFisher/CIST2100/blob/master/T2/channels.md#customer-relationships

Feel free to review and open this issue again if it doesn't meet standards. Thanks!

**Comment by GeorgLink** [comment]
Looks good. I created #20 with a minor suggestion
