### ISSUE TITLE
Key Resources

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#18]
The list of resources and key technologies is good. Please provide a short paragraph for each, describing its value as a resource to the business. Include sample software and hardware that you could purchase.

**Comment by KylePFisher** [comment]
Great feedback, you can thank @LouisNodskov for some more elaboration on https://github.com/KylePFisher/CIST2100/blob/master/T3/keyResources.md#key-resources

**Comment by GeorgLink** [comment]
Looks good. Thanks!
