### ISSUE TITLE
Financial Plan

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#28]
Good support for estimates, especially the revenue.

- Please convert the costs to tables.
- Please show the 3-year forecast with numbers for each of the three years.
- Please include the variable costs in your assessment.
- Please update table on README
- Please double check that you have all partners, resources, and processes represented in the financial estimates (you can also change the other areas, e.g, remove non-UPS shipping companies from partners).
- Consider including startup funds for registering company.

**Comment by KylePFisher** [comment]
Thanks for the feedback, you should see the changes to the README.md and the financial plan in the master branch. Let me know if you have any questions

**Comment by GeorgLink** [comment]
Thank you for addressing the comments. 

The 3-year financial plan does not reflect any changes to your business. During the first three years, it is more realistic that the business grows. Please adjust the sales, variable costs, and revenue accordingly.

**Comment by KylePFisher** [comment]
Updated with feedback. Thanks!
