### ISSUE TITLE
Structure of Repository

### ISSUE THREAD

**Issue by GeorgLink** [KylePFisher/CIST2100#9]
Please change the structure of the repository. Right now, the structure is oriented around the assignments (e.g., T1, T2, T3, sometimes still including the instructions). 

The final outcome should be an integrated business model that has sections following the business model canvas. Think of the final product as something you feel comfortable giving to the bank to ask for a startup loan. 

The README.md could serve as the central launch point to go to each section and to display the visual business model canvas. 

One idea for improvement is to use bullet points and tables to break up long sections of text and allow someone to quickly understand the core elements of your business.

**Comment by KylePFisher** [comment]
Thanks for the feedback. Per offline discussion, the README.md now has a readable business canvas model which links to our existing sections.

**Comment by GeorgLink** [comment]
Good solution. Thank you.

Maybe include a link from each section back to the README, to allow for full navigation ability across the different pages. And maybe a link to the next and previous section.
